üìä CRISP-DM Documentation
üöö Project: TransBorderFreight Data Analysis
1. Business Understanding
Transportation systems are critical to economic activity, but inefficiencies, environmental impact, and regional disparities remain ongoing challenges. This project analyzes transborder freight data from the U.S. Bureau of Transportation Statistics (BTS) to uncover insights and provide data-driven recommendations for improving the performance, safety, and sustainability of freight transportation across North America.

üìå Business Goals:
Identify dominant transportation modes and trends

Assess cost and environmental efficiency of each mode

Understand seasonal and regional patterns in freight movement

Inform strategic decisions with actionable recommendations

üîç Analytical Questions:
1 Which transportation mode handles the most freight volume and value over time?

2 Are there seasonal trends in freight movement across months and modes?

3 Which transport modes are the most cost-efficient (value per weight)?

4 How do estimated emissions compare across different transport modes?

5 Which commodities dominate cross-border freight movements?

6 Which regions (US states, Mexican states, Canadian provinces) contribute most to freight movement?

7 Which transport modes show the highest environmental impact, and where can emissions be reduced?

8 What is the overall distribution of freight value and weight over the years?

2. Data Understanding & Preprocessing
üìÅ Dataset Structure:
Source: Bureau of Transportation Statistics (BTS)

Years Covered: 2020, 2021, 2022, 2023

Merged Files: merged_2020.csv, ..., merged_2023.csv

In [19]:
import pandas as pd

# List of merged CSV files
files = ['merged_2020.csv', 'merged_2021.csv', 'merged_2022.csv', 'merged_2023.csv', 'merged_2024']

# Dictionary to store DataFrames
dataframes = {}

# Load and preview each file
for file in files:
    try:
        df = pd.read_csv(file)
        dataframes[file] = df
        print(f"üìÑ {file}: {df.shape[0]:,} rows √ó {df.shape[1]} columns")
        print(df.head(3))  # Show first 3 rows
        print("-" * 50)
    except Exception as e:
        print(f"‚ùå Could not load {file}: {e}")

C:\Users\user\AppData\Local\Temp\ipykernel_21476\3213945018.py:12: DtypeWarning: Columns (1,2,4,5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

üìÑ merged_2020.csv: 1,015,432 rows √ó 15 columns
   TRDTYPE USASTATE  DEPE  DISAGMOT MEXSTATE CANPROV  COUNTRY   VALUE  SHIPWT  \
0        1       AK  07XX         3      NaN      XA     1220    3302     378
1        1       AK  20XX         3      NaN      XA     1220  133362     137
2        1       AK  20XX         3      NaN      XA     1220   49960      66

   FREIGHT_CHARGES   DF CONTCODE  MONTH  YEAR  COMMODITY2
0              125  1.0        X      1  2020         NaN
1             1563  1.0        X      1  2020         NaN
2             2631  2.0        X      1  2020         NaN
--------------------------------------------------

C:\Users\user\AppData\Local\Temp\ipykernel_21476\3213945018.py:12: DtypeWarning: Columns (1,2,4,5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

üìÑ merged_2021.csv: 1,437,978 rows √ó 15 columns
   TRDTYPE USASTATE  DEPE  DISAGMOT MEXSTATE CANPROV  COUNTRY  VALUE  SHIPWT  \
0        1       AK  18XX         1       XX     NaN     2010   5940    1136
1        1       AK  20XX         3      NaN      XA     1220   7490      26
2        1       AK  20XX         3      NaN      XA     1220  24885      13

   FREIGHT_CHARGES   DF CONTCODE  MONTH  YEAR  COMMODITY2
0                0  1.0        1      1  2021         NaN
1              155  1.0        X      1  2021         NaN
2               78  2.0        X      1  2021         NaN
--------------------------------------------------

C:\Users\user\AppData\Local\Temp\ipykernel_21476\3213945018.py:12: DtypeWarning: Columns (1,2,4,5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

üìÑ merged_2022.csv: 1,471,797 rows √ó 15 columns
   TRDTYPE USASTATE  DEPE  DISAGMOT MEXSTATE CANPROV  COUNTRY   VALUE  SHIPWT  \
0        1       AK  0901         5      NaN      XO     1220    7042       0
1        1       AK  20XX         3      NaN      XA     1220  117977     485
2        1       AK  20XX         3      NaN      XC     1220  105057   22924

   FREIGHT_CHARGES   DF CONTCODE  MONTH  YEAR  COMMODITY2
0              137  1.0        X      1  2022         NaN
1             2181  1.0        X      1  2022         NaN
2             8899  1.0        X      1  2022         NaN
--------------------------------------------------

C:\Users\user\AppData\Local\Temp\ipykernel_21476\3213945018.py:12: DtypeWarning: Columns (1,2,4,5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

üìÑ merged_2023.csv: 1,048,575 rows √ó 15 columns
   TRDTYPE USASTATE  DEPE  DISAGMOT MEXSTATE CANPROV  COUNTRY  VALUE  SHIPWT  \
0        1       AK   708         5      NaN      XO     1220  25825       0
1        1       AK  20XX         3      NaN      XA     1220  57380     128
2        1       AK  20XX         3      NaN      XA     1220   9635      16

   FREIGHT_CHARGES   DF CONTCODE  MONTH  YEAR  COMMODITY2
0               74  2.0        X     12  2023         NaN
1             1223  1.0        X     12  2023         NaN
2              188  2.0        X     12  2023         NaN
--------------------------------------------------
‚ùå Could not load merged_2024: [Errno 2] No such file or directory: 'merged_2024'

In [20]:
for file, df in dataframes.items():
    print(f"üßæ Columns in {file}:")
    print(df.columns.tolist())
    print()

üßæ Columns in merged_2020.csv:
['TRDTYPE', 'USASTATE', 'DEPE', 'DISAGMOT', 'MEXSTATE', 'CANPROV', 'COUNTRY', 'VALUE', 'SHIPWT', 'FREIGHT_CHARGES', 'DF', 'CONTCODE', 'MONTH', 'YEAR', 'COMMODITY2']

üßæ Columns in merged_2021.csv:
['TRDTYPE', 'USASTATE', 'DEPE', 'DISAGMOT', 'MEXSTATE', 'CANPROV', 'COUNTRY', 'VALUE', 'SHIPWT', 'FREIGHT_CHARGES', 'DF', 'CONTCODE', 'MONTH', 'YEAR', 'COMMODITY2']

üßæ Columns in merged_2022.csv:
['TRDTYPE', 'USASTATE', 'DEPE', 'DISAGMOT', 'MEXSTATE', 'CANPROV', 'COUNTRY', 'VALUE', 'SHIPWT', 'FREIGHT_CHARGES', 'DF', 'CONTCODE', 'MONTH', 'YEAR', 'COMMODITY2']

üßæ Columns in merged_2023.csv:
['TRDTYPE', 'USASTATE', 'DEPE', 'DISAGMOT', 'MEXSTATE', 'CANPROV', 'COUNTRY', 'VALUE', 'SHIPWT', 'FREIGHT_CHARGES', 'DF', 'CONTCODE', 'MONTH', 'YEAR', 'COMMODITY2']

In [21]:

# Load your merged data (adjust filename as needed)
df = pd.read_csv('merged_2024.csv')  # or merged_2021.csv etc.

# 1. Shape of data
print(f"üìä Shape: {df.shape}")

# 2. Column names
print("üìå Columns:", df.columns.tolist())

# 3. Data types
print("\nüîé Data Types:\n", df.dtypes)

# 4. Missing values
print("\n‚ùì Missing Values:\n", df.isnull().sum())

# 5. Summary statistics for numeric columns
print("\nüìà Summary Stats:\n", df.describe())

# 6. Unique values for key columns
key_columns = ['DISAGMOT', 'COUNTRY', 'USASTATE', 'MEXSTATE', 'CANPROV', 'MONTH', 'YEAR', 'COMMODITY2']
for col in key_columns:
    print(f"\nüßæ Unique values in {col}: {df[col].unique()}")

C:\Users\user\AppData\Local\Temp\ipykernel_21476\2170273507.py:2: DtypeWarning: Columns (2,4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('merged_2024.csv')  # or merged_2021.csv etc.

üìä Shape: (1108543, 16)
üìå Columns: ['TRDTYPE', 'USASTATE', 'DEPE', 'DISAGMOT', 'MEXSTATE', 'CANPROV', 'COUNTRY', 'VALUE', 'SHIPWT', 'FREIGHT_CHARGES', 'DF', 'CONTCODE', 'MONTH', 'YEAR', 'source_folder', 'COMMODITY2']

üîé Data Types:
 TRDTYPE              int64
USASTATE            object
DEPE                object
DISAGMOT             int64
MEXSTATE            object
CANPROV             object
COUNTRY              int64
VALUE                int64
SHIPWT               int64
FREIGHT_CHARGES      int64
DF                 float64
CONTCODE            object
MONTH                int64
YEAR                 int64
source_folder       object
COMMODITY2         float64
dtype: object

‚ùì Missing Values:
 TRDTYPE                 0
USASTATE           138997
DEPE               708443
DISAGMOT                0
MEXSTATE           779006
CANPROV            530602
COUNTRY                 0
VALUE                   0
SHIPWT                  0
FREIGHT_CHARGES         0
DF                 364301
CONTCODE                0
MONTH                   0
YEAR                    0
source_folder           0
COMMODITY2         261103
dtype: int64

üìà Summary Stats:
             TRDTYPE      DISAGMOT       COUNTRY         VALUE        SHIPWT  \
count  1.108543e+06  1.108543e+06  1.108543e+06  1.108543e+06  1.108543e+06
mean   1.328630e+00  4.769996e+00  1.540492e+03  3.140394e+06  1.146334e+06
std    4.697155e-01  1.262878e+00  3.879095e+02  4.288252e+07  4.177479e+07
min    1.000000e+00  1.000000e+00  1.220000e+03  0.000000e+00  0.000000e+00
25%    1.000000e+00  5.000000e+00  1.220000e+03  1.475600e+04  0.000000e+00
50%    1.000000e+00  5.000000e+00  1.220000e+03  7.523100e+04  0.000000e+00
75%    2.000000e+00  5.000000e+00  2.010000e+03  4.556945e+05  1.824000e+03
max    2.000000e+00  9.000000e+00  2.010000e+03  5.595625e+09  8.729049e+09

       FREIGHT_CHARGES             DF         MONTH       YEAR     COMMODITY2
count     1.108543e+06  744242.000000  1.108543e+06  1108543.0  847440.000000
mean      3.772386e+04       1.333789  5.045023e+00     2024.0      57.099390
std       1.078433e+06       0.471566  2.574308e+00        0.0      27.736793
min       0.000000e+00       1.000000  1.000000e+00     2024.0       1.000000
25%       0.000000e+00       1.000000  3.000000e+00     2024.0      34.000000
50%       2.500000e+02       1.000000  5.000000e+00     2024.0      61.000000
75%       2.750000e+03       2.000000  7.000000e+00     2024.0      84.000000
max       2.389452e+08       2.000000  9.000000e+00     2024.0      99.000000

üßæ Unique values in DISAGMOT: [5 1 3 8 6 7 4 9]

üßæ Unique values in COUNTRY: [1220 2010]

üßæ Unique values in USASTATE: ['AK' 'AL' 'AR' 'AZ' 'CA' 'CO' 'CT' 'DC' 'DE' 'DU' 'FL' 'GA' 'HI' 'IA'
 'ID' 'IL' 'IN' 'KS' 'KY' 'LA' 'MA' 'MD' 'ME' 'MI' 'MN' 'MO' 'MS' 'MT'
 'NC' 'ND' 'NE' 'NH' 'NJ' 'NM' 'NV' 'NY' 'OH' 'OK' 'OR' 'PA' 'RI' 'SC'
 'SD' 'TN' 'TX' 'UT' 'VA' 'VT' 'WA' 'WI' 'WV' 'WY' nan]

üßæ Unique values in MEXSTATE: [nan 'XX' 'MX' 'CH' 'CM' 'CO' 'GT' 'NL' 'QT' 'SL' 'TL' 'TM' 'JA' 'BC' 'OT'
 'ZA' 'DF' 'DG' 'AG' 'HG' 'MI' 'MO' 'PU' 'SO' 'TB' 'VE' 'YU' 'OA' 'SI'
 'QR' 'BS' 'CL' 'GR' 'CS']

üßæ Unique values in CANPROV: ['XQ' 'XY' nan 'XA' 'XC' 'XM' 'XO' 'XS' 'XB' 'OT' 'XN' 'XP' 'XW' 'XT' 'XV']

üßæ Unique values in MONTH: [4 8 2 1 7 6 3 5 9]

üßæ Unique values in YEAR: [2024]

üßæ Unique values in COMMODITY2: [nan  2.  3.  5.  7. 15. 20. 23. 27. 32. 39. 40. 41. 42. 44. 62. 63. 68.
 70. 72. 73. 76. 82. 83. 84. 85. 86. 87. 88. 90. 91. 98.  1.  4.  6.  9.
 12. 16. 17. 19. 21. 22. 25. 28. 29. 30. 31. 33. 34. 35. 36. 38. 46. 47.
 48. 49. 53. 54. 55. 56. 57. 58. 59. 60. 61. 64. 65. 69. 71. 74. 75. 78.
 80. 81. 89. 92. 94. 95. 96.  8. 10. 11. 26. 52. 79. 93. 13. 14. 18. 24.
 37. 45. 97. 43. 50. 51. 66. 67. 99.]

In [22]:
def get_origin_with_country(row):
    if pd.notna(row['USASTATE']):
        return f"US-{row['USASTATE']}"
    elif pd.notna(row['MEXSTATE']):
        return f"MX-{row['MEXSTATE']}"
    elif pd.notna(row['CANPROV']):
        return f"CA-{row['CANPROV']}"
    else:
        return 'Unknown'

df['origin_region'] = df.apply(get_origin_with_country, axis=1)

In [23]:
# Replace NaN with "Unknown" in relevant columns
df['USASTATE'] = df['USASTATE'].fillna('Unknown')
df['MEXSTATE'] = df['MEXSTATE'].fillna('Unknown')
df['CANPROV']  = df['CANPROV'].fillna('Unknown')

In [24]:
def clean_location(value):
    return value if pd.notnull(value) else "Unknown"

def get_route_description(row):
    us_state = clean_location(row['USASTATE'])
    mex_state = clean_location(row['MEXSTATE'])
    can_prov = clean_location(row['CANPROV'])
    
    if row['TRDTYPE'] == 1:  # Import to US
        if row['COUNTRY'] == 1220:  # Canada
            return f"Import from Canada-{can_prov} to US-{us_state}"
        elif row['COUNTRY'] == 2010:  # Mexico
            return f"Import from Mexico-{mex_state} to US-{us_state}"
        else:
            return f"Import from Unknown to US-{us_state}"
        
    elif row['TRDTYPE'] == 2:  # Export from US
        if row['COUNTRY'] == 1220:  # Canada
            return f"Export from US-{us_state} to Canada-{can_prov}"
        elif row['COUNTRY'] == 2010:  # Mexico
            return f"Export from US-{us_state} to Mexico-{mex_state}"
        else:
            return f"Export from US-{us_state} to Unknown"
    else:
        return "Unknown route"

# Apply the function
df['route_description'] = df.apply(get_route_description, axis=1)

In [25]:
df.head(10)

,TRDTYPE,USASTATE,DEPE,DISAGMOT,MEXSTATE,CANPROV,COUNTRY,VALUE,SHIPWT,FREIGHT_CHARGES,DF,CONTCODE,MONTH,YEAR,source_folder,COMMODITY2,origin_region,route_description
0,1,AK,0712,5,Unknown,XQ,1220,14609,0,286,1.0,X,4,2024,April2024,NaN,US-AK,Import from Canada-XQ to US-AK
1,1,AK,0901,5,Unknown,XY,1220,26482,0,26,1.0,X,4,2024,April2024,NaN,US-AK,Import from Canada-XY to US-AK
2,1,AK,19XX,1,XX,Unknown,2010,72786,40210,0,1.0,0,4,2024,April2024,NaN,US-AK,Import from Mexico-XX to US-AK
3,1,AK,20XX,3,Unknown,XA,1220,111914,775,980,1.0,X,4,2024,April2024,NaN,US-AK,Import from Canada-XA to US-AK
4,1,AK,20XX,3,Unknown,XA,1220,24831,63,178,2.0,X,4,2024,April2024,NaN,US-AK,Import from Canada-XA to US-AK
5,1,AK,20XX,3,Unknown,XC,1220,78214,225,1080,1.0,X,4,2024,April2024,NaN,US-AK,Import from Canada-XC to US-AK
6,1,AK,20XX,3,Unknown,XM,1220,21835,47,72,1.0,X,4,2024,April2024,NaN,US-AK,Import from Canada-XM to US-AK
7,1,AK,20XX,3,Unknown,XO,1220,35490,616,776,1.0,X,4,2024,April2024,NaN,US-AK,Import from Canada-XO to US-AK
8,1,AK,20XX,3,Unknown,XQ,1220,63052,4128,2608,1.0,X,4,2024,April2024,NaN,US-AK,Import from Canada-XQ to US-AK
9,1,AK,20XX,3,Unknown,XQ,1220,3353,13,65,2.0,X,4,2024,April2024,NaN,US-AK,Import from Canada-XQ to US-AK

In [26]:
df['COMMODITY2'] = df['COMMODITY2'].fillna("Unknown")
df['DEPE'] = df['DEPE'].fillna('Unknown')
df['DF'] = df['DF'].fillna('Unknown')

In [27]:
# Display all unique values for each column
for col in df.columns:
    print(f"\nüßæ Unique values in '{col}':")
    print(df[col].unique())

üßæ Unique values in 'TRDTYPE':
[1 2]

üßæ Unique values in 'USASTATE':
['AK' 'AL' 'AR' 'AZ' 'CA' 'CO' 'CT' 'DC' 'DE' 'DU' 'FL' 'GA' 'HI' 'IA'
 'ID' 'IL' 'IN' 'KS' 'KY' 'LA' 'MA' 'MD' 'ME' 'MI' 'MN' 'MO' 'MS' 'MT'
 'NC' 'ND' 'NE' 'NH' 'NJ' 'NM' 'NV' 'NY' 'OH' 'OK' 'OR' 'PA' 'RI' 'SC'
 'SD' 'TN' 'TX' 'UT' 'VA' 'VT' 'WA' 'WI' 'WV' 'WY' 'Unknown']

üßæ Unique values in 'DEPE':
['0712' '0901' '19XX' '20XX' '2303' '2304' '2305' '2408' '2506' '2604'
 '3004' '3009' '3023' '30XX' '3101' '3103' '3104' '3106' '3126' '31XX'
 '3310' '33XX' '3401' '3403' '34XX' '35XX' '3801' '3802' '4101' '41XX'
 '53XX' '70XX' '0106' '0115' '0206' '0209' '0701' '0708' '07XX' '09XX'
 '14XX' '17XX' '18XX' '2301' '2401' '2402' '2403' '2404' '2503' '2507'
 '2601' '2603' '2608' '2720' '3001' '3002' '3003' '3019' '3301' '3302'
 '3322' '3407' '3501' '3604' '3613' '3803' '38XX' '4102' '5203' '52XX'
 '55XX' '2006' '2504' '2505' '3005' '3016' '3422' '39XX' '0212' '02XX'
 '0704' '0715' '11XX' '1704' '2307' '2310' '2602' '2605' '2609' '26XX'
 '27XX' '2801' '3007' '3008' '3020' '4115' '5201' '5501' '0101' '0103'
 '01XX' '0417' '1003' '1012' '10XX' '16XX' '2302' '2309' '2406' '2501'
 '25XX' '2704' '28XX' '29XX' '3013' '3102' '3304' '3308' '3316' '3318'
 '3410' '3413' '36XX' '3804' '3819' '3901' '4103' '4105' '4110' '54XX'
 '3307' '0104' '0211' '04XX' '13XX' '3424' '0706' '4104' '49XX' '80XX'
 '0105' '0108' '3010' '3805' '37XX' '32XX' '3406' '0127' '3025' '3303'
 '3305' '3306' '0107' '0118' '15XX' '3012' '3404' '0207' '3321' '3430'
 '3809' '4504' '45XX' '5301' '0203' '2007' '0102' '0109' '0110' '0111'
 '0112' '0714' '0903' '3701' '2606' '3309' '3317' '3325' '1502' '3405'
 '3409' '3414' '3415' '3417' '3419' '3420' '3421' '3426' '3015' '3017'
 '0904' '0905' '3411' '3808' '59XX' '05XX' '21XX' '24XX' '2502' '3323'
 '3014' '3022' '3026' '3029' '3111' '3115' '0906' '23XX' '3423' '3807'
 '51XX' '60XX' '1303' '1902' '3806' '3427' '3434' '1603' '0131' '3006'
 'Unknown' '3105' '3011' '3425' '3408' '3814' '3416' '3815' '0201' '3816'
 '3018' '2407' '3882' '2383' 101.0 102.0 103.0 104.0 105.0 106.0 '3433'
 '3324' '0121' '3881' '2481' '3843' '3818']

üßæ Unique values in 'DISAGMOT':
[5 1 3 8 6 7 4 9]

üßæ Unique values in 'MEXSTATE':
['Unknown' 'XX' 'MX' 'CH' 'CM' 'CO' 'GT' 'NL' 'QT' 'SL' 'TL' 'TM' 'JA'
 'BC' 'OT' 'ZA' 'DF' 'DG' 'AG' 'HG' 'MI' 'MO' 'PU' 'SO' 'TB' 'VE' 'YU'
 'OA' 'SI' 'QR' 'BS' 'CL' 'GR' 'CS']

üßæ Unique values in 'CANPROV':
['XQ' 'XY' 'Unknown' 'XA' 'XC' 'XM' 'XO' 'XS' 'XB' 'OT' 'XN' 'XP' 'XW'
 'XT' 'XV']

üßæ Unique values in 'COUNTRY':
[1220 2010]

üßæ Unique values in 'VALUE':
[  14609   26482   72786 ... 1168062 4384342  793390]

üßæ Unique values in 'SHIPWT':
[      0   40210     775 ... 9137618  429110   16276]

üßæ Unique values in 'FREIGHT_CHARGES':
[   286     26      0 ...  36155 391893  38564]

üßæ Unique values in 'DF':
[1.0 2.0 'Unknown']

üßæ Unique values in 'CONTCODE':
['X' '0' '1']

üßæ Unique values in 'MONTH':
[4 8 2 1 7 6 3 5 9]

üßæ Unique values in 'YEAR':
[2024]

üßæ Unique values in 'source_folder':
['April2024' 'Aug2024' 'Feb2024' 'Jan2024' 'July2024' 'June2024'
 'March2024' 'May2024' 'sept2024']

üßæ Unique values in 'COMMODITY2':
['Unknown' 2.0 3.0 5.0 7.0 15.0 20.0 23.0 27.0 32.0 39.0 40.0 41.0 42.0
 44.0 62.0 63.0 68.0 70.0 72.0 73.0 76.0 82.0 83.0 84.0 85.0 86.0 87.0
 88.0 90.0 91.0 98.0 1.0 4.0 6.0 9.0 12.0 16.0 17.0 19.0 21.0 22.0 25.0
 28.0 29.0 30.0 31.0 33.0 34.0 35.0 36.0 38.0 46.0 47.0 48.0 49.0 53.0
 54.0 55.0 56.0 57.0 58.0 59.0 60.0 61.0 64.0 65.0 69.0 71.0 74.0 75.0
 78.0 80.0 81.0 89.0 92.0 94.0 95.0 96.0 8.0 10.0 11.0 26.0 52.0 79.0 93.0
 13.0 14.0 18.0 24.0 37.0 45.0 97.0 43.0 50.0 51.0 66.0 67.0 99.0]

üßæ Unique values in 'origin_region':
['US-AK' 'US-AL' 'US-AR' 'US-AZ' 'US-CA' 'US-CO' 'US-CT' 'US-DC' 'US-DE'
 'US-DU' 'US-FL' 'US-GA' 'US-HI' 'US-IA' 'US-ID' 'US-IL' 'US-IN' 'US-KS'
 'US-KY' 'US-LA' 'US-MA' 'US-MD' 'US-ME' 'US-MI' 'US-MN' 'US-MO' 'US-MS'
 'US-MT' 'US-NC' 'US-ND' 'US-NE' 'US-NH' 'US-NJ' 'US-NM' 'US-NV' 'US-NY'
 'US-OH' 'US-OK' 'US-OR' 'US-PA' 'US-RI' 'US-SC' 'US-SD' 'US-TN' 'US-TX'
 'US-UT' 'US-VA' 'US-VT' 'US-WA' 'US-WI' 'US-WV' 'US-WY' 'Unknown']

üßæ Unique values in 'route_description':
['Import from Canada-XQ to US-AK' 'Import from Canada-XY to US-AK'
 'Import from Mexico-XX to US-AK' ... 'Import from Mexico-MO to US-WV'
 'Export from US-HI to Canada-XW' 'Export from US-NM to Canada-XV']

In [28]:
import json

# Define mappings based on the dataset and known codebook
mappings = {
    "TRDTYPE": {
        1: "Export",
        2: "Import"
    },
    "DISAGMOT": {
  "1": "Vessel",
  "3": "Air",
  "4": "Mail",
  "5": "Truck",
  "6": "Rail",
  "7": "Pipeline",
  "8": "Other",
  "9": "FTZ"
},
    "DF": {
        1.0: "Domestic",
        2.0: "Foreign",
        "Unknown": "Unknown"
    },
    "CONTCODE": {
        "X": "Containerized",
        "0": "Not containerized",
        "1": "Unknown"
    },
    "COUNTRY": {
        1220: "Canada",
        2010: "Mexico"
    },
    "COMMODITY2": {
  "01": "Live animals",
  "02": "Meat & offal",
  "03": "Fish & seafood",
  "04": "Dairy & eggs",
  "05": "Other animal products",
  "06": "Live plants & flowers",
  "07": "Vegetables & roots",
  "08": "Fruits & nuts",
  "09": "Coffee & spices",
  "10": "Cereals",
  "11": "Milling products",
  "12": "Seeds & fodder",
  "13": "Gums & resins",
  "14": "Other veg products",
  "15": "Fats & oils",
  "16": "Meat/fish prep",
  "17": "Sugars & sweets",
  "18": "Cocoa products",
  "19": "Cereal prep & baking",
  "20": "Fruit/veg prep",
  "21": "Other edibles",
  "22": "Drinks & alcohol",
  "23": "Animal feed",
  "24": "Tobacco",
  "25": "Salt, stone, cement",
  "26": "Ores & ash",
  "27": "Fuels & oils",
  "28": "Inorganic chemicals",
  "29": "Organic chemicals",
  "30": "Pharma products",
  "31": "Fertilizers",
  "32": "Dyes, paints, inks",
  "33": "Perfumes & cosmetics",
  "34": "Soaps & waxes",
  "35": "Glues & enzymes",
  "36": "Explosives & matches",
  "37": "Photo goods",
  "38": "Misc. chemicals",
  "39": "Plastics",
  "40": "Rubber",
  "41": "Hides & leather",
  "42": "Leather goods",
  "43": "Furs & products",
  "44": "Wood & charcoal",
  "45": "Cork",
  "46": "Straw & wicker",
  "47": "Wood pulp & scrap",
  "48": "Paper & board",
  "49": "Books & printed",
  "50": "Silk",
  "51": "Wool & hair",
  "52": "Cotton",
  "53": "Other textiles",
  "54": "Man-made filaments",
  "55": "Staple fibers",
  "56": "Felt, rope & cords",
  "57": "Carpets",
  "58": "Lace & embroidery",
  "59": "Coated textiles",
  "60": "Knitted fabrics",
  "61": "Knitwear",
  "62": "Woven clothing",
  "63": "Other textiles",
  "64": "Footwear",
  "65": "Headgear",
  "66": "Umbrellas & sticks",
  "67": "Feathers & hair",
  "68": "Stone & similar",
  "69": "Ceramics",
  "70": "Glassware",
  "71": "Jewelry & coins",
  "72": "Iron & steel",
  "73": "Iron/steel articles",
  "74": "Copper products",
  "75": "Nickel products",
  "76": "Aluminum products",
  "77": "Reserved",
  "78": "Lead products",
  "79": "Zinc products",
  "80": "Tin products",
  "81": "Other metals",
  "82": "Tools & cutlery",
  "83": "Other base metal goods",
  "84": "Machinery",
  "85": "Electronics",
  "86": "Railway equipment",
  "87": "Vehicles",
  "88": "Aircraft & parts",
  "89": "Boats & ships",
  "90": "Precision instruments",
  "91": "Watches & parts",
  "92": "Musical instruments",
  "93": "Arms & ammo",
  "94": "Furniture & lighting",
  "95": "Toys & sports gear",
  "96": "Misc. goods",
  "97": "Art & antiques",
  "98": "Special provisions",
  "99": "Temporary imports",
  "Unknown": "Unknown"
},
"USASTATE" : {
    "AL": "Alabama",
    "AK": "Alaska",
    "AS": "American Samoa",
    "AZ": "Arizona",
    "AR": "Arkansas",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DE": "Delaware",
    "DC": "District of Columbia",
    "FL": "Florida",
    "GA": "Georgia",
    "HI": "Hawaii",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "IA": "Iowa",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "ME": "Maine",
    "MD": "Maryland",
    "MA": "Massachusetts",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MS": "Mississippi",
    "MO": "Missouri",
    "MT": "Montana",
    "NE": "Nebraska",
    "NV": "Nevada",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NY": "New York",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PA": "Pennsylvania",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VT": "Vermont",
    "VA": "Virginia",
    "WA": "Washington",
    "WV": "West Virginia",
    "WI": "Wisconsin",
    "WY": "Wyoming",
    "DU": "Unknown",
    "Unknown": "Unknown"
},
"MEXSTATE" : {
    "AG": "Aguascalientes",
    "BC": "Baja California",
    "BN": "Baja California Norte",
    "BS": "Baja California Sur",
    "CH": "Chihuahua",
    "CL": "Colima",
    "CM": "Campeche",
    "CO": "Coahuila",
    "CS": "Chiapas",
    "DF": "Distrito Federal",
    "DG": "Durango",
    "GR": "Guerrero",
    "GT": "Guanajuato",
    "HG": "Hidalgo",
    "JA": "Jalisco",
    "MI": "Michoac√°n",
    "MO": "Morelos",
    "MX": "Estado de Mexico",
    "NA": "Nayarit",
    "NL": "Nuevo Leon",
    "OA": "Oaxaca",
    "PU": "Puebla",
    "QR": "Quintana Roo",
    "QT": "Queretaro",
    "SI": "Sinaloa",
    "SL": "San Luis Potosi",
    "SO": "Sonora",
    "TB": "Tabasco",
    "TL": "Tlaxcala",
    "TM": "Tamaulipas",
    "VE": "Veracruz",
    "YU": "Yucatan",
    "ZA": "Zacatecas",
    "OT": "Unknown",
    "XX": "Unknown",
    "Unknown": "Unknown"
},
"CANPROV" : {
    "XA": "Alberta",
    "XC": "British Columbia",
    "XM": "Manitoba",
    "XB": "New Brunswick",
    "XW": "Newfoundland",
    "XT": "Northwest Territories",
    "XN": "Nova Scotia",
    "XO": "Ontario",
    "XP": "Prince Edward Island",
    "XQ": "Quebec",
    "XS": "Saskatchewan",
    "XV": "Nunavut",
    "XY": "Yukon Territory",
    "OT": "Unknown",
    "Unknown": "Unknown"
}

}


# Save to JSON file
file_path = "column_mappings.json"
with open(file_path, "w") as f:
    json.dump(mappings, f, indent=4)

file_path

'column_mappings.json'

In [29]:
import pandas as pd
import json

# Load mapping
with open("column_mappings.json") as f:
    code_mappings = json.load(f)

# --- Ensure correct dtype and mapping for each column ---

# COMMODITY2: convert to str keys like "01", "02", etc.
df['COMMODITY2'] = pd.to_numeric(df['COMMODITY2'], errors='coerce')
df['COMMODITY2_MAPPED'] = (
    df['COMMODITY2']
    .dropna()
    .astype(int)
    .astype(str)
    .map(code_mappings['COMMODITY2'])
)
df['COMMODITY2_MAPPED'] = df['COMMODITY2_MAPPED'].fillna('Unknown')

# DISAGMOT
df['DISAGMOT_MAPPED'] = df['DISAGMOT'].astype(str).map(code_mappings['DISAGMOT'])

# TRDTYPE
df['TRDTYPE_MAPPED'] = df['TRDTYPE'].astype(str).map(code_mappings['TRDTYPE'])

# DF
df['DF_MAPPED'] = df['DF'].astype(str).map(code_mappings['DF'])

# CONTCODE
df['CONTCODE_MAPPED'] = df['CONTCODE'].map(code_mappings['CONTCODE'])

# COUNTRY
df['COUNTRY_MAPPED'] = df['COUNTRY'].astype(str).map(code_mappings['COUNTRY'])

df['USASTATE_MAPPED'] = df['USASTATE'].map(code_mappings['USASTATE']).fillna('Unknown')
df['MEXSTATE_MAPPED'] = df['MEXSTATE'].map(code_mappings['MEXSTATE']).fillna('Unknown')
df['CANPROV_MAPPED'] = df['CANPROV'].map(code_mappings['CANPROV']).fillna('Province Unknown')




# Final check (optional)
mapped_columns = [col for col in df.columns if col.endswith('_MAPPED')]
print(df[mapped_columns].head())

  COMMODITY2_MAPPED DISAGMOT_MAPPED TRDTYPE_MAPPED DF_MAPPED  \
0           Unknown           Truck         Export  Domestic
1           Unknown           Truck         Export  Domestic
2           Unknown          Vessel         Export  Domestic
3           Unknown             Air         Export  Domestic
4           Unknown             Air         Export   Foreign

     CONTCODE_MAPPED COUNTRY_MAPPED USASTATE_MAPPED MEXSTATE_MAPPED  \
0      Containerized         Canada          Alaska         Unknown
1      Containerized         Canada          Alaska         Unknown
2  Not containerized         Mexico          Alaska         Unknown
3      Containerized         Canada          Alaska         Unknown
4      Containerized         Canada          Alaska         Unknown

    CANPROV_MAPPED
0           Quebec
1  Yukon Territory
2          Unknown
3          Alberta
4          Alberta

In [30]:
df['DEPE'] = df['DEPE'].astype(str)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1108543 entries, 0 to 1108542
Data columns (total 27 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   TRDTYPE            1108543 non-null  int64
 1   USASTATE           1108543 non-null  object
 2   DEPE               1108543 non-null  object
 3   DISAGMOT           1108543 non-null  int64
 4   MEXSTATE           1108543 non-null  object
 5   CANPROV            1108543 non-null  object
 6   COUNTRY            1108543 non-null  int64
 7   VALUE              1108543 non-null  int64
 8   SHIPWT             1108543 non-null  int64
 9   FREIGHT_CHARGES    1108543 non-null  int64
 10  DF                 1108543 non-null  object
 11  CONTCODE           1108543 non-null  object
 12  MONTH              1108543 non-null  int64
 13  YEAR               1108543 non-null  int64
 14  source_folder      1108543 non-null  object
 15  COMMODITY2         847440 non-null   float64
 16  origin_region      1108543 non-null  object
 17  route_description  1108543 non-null  object
 18  COMMODITY2_MAPPED  1108543 non-null  object
 19  DISAGMOT_MAPPED    1108543 non-null  object
 20  TRDTYPE_MAPPED     1108543 non-null  object
 21  DF_MAPPED          1108543 non-null  object
 22  CONTCODE_MAPPED    1108543 non-null  object
 23  COUNTRY_MAPPED     1108543 non-null  object
 24  USASTATE_MAPPED    1108543 non-null  object
 25  MEXSTATE_MAPPED    1108543 non-null  object
 26  CANPROV_MAPPED     1108543 non-null  object
dtypes: float64(1), int64(8), object(18)
memory usage: 228.4+ MB

In [31]:
columns_to_drop = [
    'TRDTYPE',
    'DISAGMOT',
    'DF',
    'CONTCODE',
    'COUNTRY',
    'COMMODITY2',
    'USASTATE',
    'MEXSTATE',
    'CANPROV'
]

df.drop(columns=columns_to_drop, inplace=True)

# Confirm
print("Remaining columns:", df.columns.tolist())

Remaining columns: ['DEPE', 'VALUE', 'SHIPWT', 'FREIGHT_CHARGES', 'MONTH', 'YEAR', 'source_folder', 'origin_region', 'route_description', 'COMMODITY2_MAPPED', 'DISAGMOT_MAPPED', 'TRDTYPE_MAPPED', 'DF_MAPPED', 'CONTCODE_MAPPED', 'COUNTRY_MAPPED', 'USASTATE_MAPPED', 'MEXSTATE_MAPPED', 'CANPROV_MAPPED']

In [32]:
df.isnull().sum()

DEPE                 0
VALUE                0
SHIPWT               0
FREIGHT_CHARGES      0
MONTH                0
YEAR                 0
source_folder        0
origin_region        0
route_description    0
COMMODITY2_MAPPED    0
DISAGMOT_MAPPED      0
TRDTYPE_MAPPED       0
DF_MAPPED            0
CONTCODE_MAPPED      0
COUNTRY_MAPPED       0
USASTATE_MAPPED      0
MEXSTATE_MAPPED      0
CANPROV_MAPPED       0
dtype: int64

In [33]:
df.to_csv("cleaned_2024.csv", index=False)